### ISSUE TITLE
how to create certificates for xamarin Ios app 

### ISSUE THREAD

**Issue by MSidda** [IeuanWalker/BankingApplication#2]
please help me ,i want to build ios app using vsts tool...provide build steps
Thanks

**Comment by IeuanWalker** [comment]
@MSidda sorry this is a Java console application and has nothing to do with Azure Devops (VSTS) or iOS.
But this might help - [Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops)
